### ISSUE TITLE
Failure in createVolume Task

### ISSUE THREAD

**Issue by astoklas** [purestorage/ucs-director-plugin#8]
The UCSD CreateVolume Task fails with the message HTTP 400 - {"msg": "The following arguments are mutually exclusive: [['size'], ['source']]."}

Pure Version used 4.7.3 (API 1.6)

Error Message:
2016-11-24 17:12:18,442 [WFExec-17-1] ERROR executeWorkFlowStep(CustomActionTriggerWorkFlowHandler.java:359) - Custom handler exception; Task: create-volume (Create Volume(s)-suffix range) failed with error - 
com.purestorage.rest.exceptions.ClientErrorException: HTTP 400 - {"msg": "The following arguments are mutually exclusive: [['size'], ['source']]."}
	at com.purestorage.rest.PureRestClientImpl.validateResponseCode(PureRestClientImpl.java:467)
	at com.purestorage.rest.PureRestClientImpl.createConnection(PureRestClientImpl.java:427)
	at com.purestorage.rest.PureRestClientImpl.access$300(PureRestClientImpl.java:58)
	at com.purestorage.rest.PureRestClientImpl$1.apply(PureRestClientImpl.java:296)
	at com.purestorage.rest.PureRestClientImpl$1.apply(PureRestClientImpl.java:292)
	at com.purestorage.rest.PureRestClientImpl.sendWithRetries(PureRestClientImpl.java:371)
	at com.purestorage.rest.PureRestClientImpl.sendWithRetries(PureRestClientImpl.java:291)
	at com.purestorage.rest.PureRestClientImpl.sendRequest(PureRestClientImpl.java:251)
	at com.purestorage.rest.operations.PureVolumeOperationsImpl.create(PureVolumeOperationsImpl.java:21)
	at com.cloupia.feature.purestorage.tasks.NewVolumeTask.executeCustomAction(NewVolumeTask.java:109)
	at com.cloupia.service.cIM.inframgr.workflowhandlers.CustomActionTriggerWorkFlowHandler.executeWorkFlowStep(CustomActionTriggerWorkFlowHandler.java:293)
	at com.cloupia.service.cIM.inframgr.workflowmgr.WorkFlowExecutor.run(WorkFlowExecutor.java:96)

**Comment by saif-cl0ud** [comment]
Resolved in latest connector.
